
optical_dedup: False
instrument: generic
platform: generic
libprep: generic


# if using fastp null read filtering, these can be ignored
min_read_qual: 15
min_avg_qual: 13
read_length: 100
minlen: 33
maxlen: 325

# use base correction for fastp (eg. for denovo-assembling, etc)
correction: False

# for WGS data, deduplicate is important
deduplicate: True

# whether to keep bam files in any of the steps 
keep_paired_bam: False
keep_proper_bam: False
keep_filtered_bam: False
keep_deduplicated_bam: False
keep_final_bam: False
keep_recalibrated_bam: False


# reference sequence, reference map, known variants for base recalibration, etc
refseq_file: refs/PvP01_v1.fasta
refmap_file: refs/PvP01_v1.mmi
knownsites_file: refs/pv-known-variants.bed.gz
knownvariants_dir: refs/known-variants

# parameter for bwa-mem2
bwamem2_flags: null
bwamem2_extra_flags: null

# filter to apply for deduplicated BAM
# read_filters options:
# --remove_FR --remove_RF --remove_FF --remove_RR : removing by orientation (Front, Reverse)
# --remove_trans : remove pair of reads that map to different chromosomes
# --remove_unmapped : remove pair or reads whose any of the pair is unmapped
# --remove_secondary --remove_supplementary : remove secondary & supplementary maps
# for below, we keep FR, RF, FF and RR orientation for future SV analysis
read_filters: --remove_trans --remove_unmapped --remove_secondary --remove_supplementary

# snakemake to use:

reads_trimmer_wf: trimmer_null.smk
reads_mapper_wf: mapper_bwa-mem2.smk

# parameter for joint variant calling
variant_file: null
interval_file: null
interval_dir: null

# java options (for GATK)
java_opts:

# -- options for individual software in used --
applybqsr_extra_flags:
applybqsr_flags:

baserecalibrator_extra_flags:
baserecalibrator_flags:

freebayes_extra_flags:

gatherbqsrr_extra_flags:
gatherbqsrr_flags:

haplotypecaller_extra_flags:
haplotypecaller_flags:

ggvcf_flags: -stand-call-conf 10 -new-qual
ggvcf_extra_flags: 



# -- options for multistep variant calling --

# if we need to run outside NGSENV_BASEDIR, set to: --force
prepare_sample_directory_flags:

# if we need to run outside NGSENV_BASEDIR, set to: --force --no-config-cascade
sample_variant_caller_flags:
joint_variant_caller_flags:


# -- options for regions to filter --

# regions to be analyzed
regions:
  - PvP01_14_v1
  - PvP01_13_v1
  - PvP01_12_v1
  - PvP01_11_v1
  - PvP01_10_v1
  - PvP01_09_v1
  - PvP01_08_v1
  - PvP01_07_v1
  - PvP01_06_v1
  - PvP01_05_v1
  - PvP01_04_v1
  - PvP01_03_v1
  - PvP01_02_v1
  - PvP01_01_v1
  - PvP01_API_v1
  - PvP01_MIT_v1

# regions to be considered as contaminant whose mapped reads
# will be removed right after mapping

contaminant_regions:
  - NC_000001.11
  - NC_000002.12
  - NC_000003.12
  - NC_000004.12
  - NC_000005.10
  - NC_000006.12
  - NC_000007.14
  - NC_000008.11
  - NC_000009.12
  - NC_000010.11
  - NC_000011.10
  - NC_000012.12
  - NC_000013.11
  - NC_000014.9
  - NC_000015.10
  - NC_000016.10
  - NC_000017.11
  - NC_000018.10
  - NC_000019.10
  - NC_000020.11
  - NC_000021.9
  - NC_000022.11
  - NC_000023.11
  - NC_000024.10
  - NC_012920.1



# EOF
