#!/usr/bin/env bash

# set prompt and history


if [ -n ${NGS_PROMPT:-} ]; then
    
    PS1="(${NGS_PROMPT}) [\u@\h \W]\$ "
    HIST_EXT=${NGS_PROMPT}

fi

# set history

if [ -n ${HIST_EXT:-} ]; then

    export HISTFILE=${HOME}/.bash_history.${HIST_EXT}

    HISTSIZE=20000
    HISTFILESIZE=20000
    history -c; history -r

fi

# EOF
